name: Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # обновление раз в сутки
  workflow_dispatch:       # возможность запускать руками
  push:
    branches: ["main"]     # поменяй на master, если у тебя master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: MustafaProger          # ← твой ник
          BRANCH: master                     # ← замени на master, если нужно
          THEME: tokyonight                # тёмная тема (можно dracula/monokai/github_dark/gruvbox)
